import type { ImpactSummary } from "./types"

/**
 * Period slice of launchpad “captured” opportunity ($1.84M YTD).
 * Numbers are sized so table impacts roughly reconcile to Incremental Sales.
 */
export const impactSummary: ImpactSummary = {
  dateRangeLabel: "Aug 13 - Sep 11, 2026",
  brands: [
    "All Brands",
    "Yankee Candle",
    "Dyson",
    "KitchenAid",
    "Instant Pot",
    "Shark",
    "Vitamix",
    "iRobot",
    "NutriChef",
    "Proctor Silex",
    "Vevor",
  ],
  metrics: [
    {
      id: "incremental-sales",
      label: "Incremental Sales",
      value: "$246,480",
      valueTone: "success",
      supportLead: "+18%",
      support: "vs prior period",
    },
    {
      id: "incremental-units",
      label: "Incremental Units Sold",
      value: "4,820",
      support: "Across measurable events",
    },
    {
      id: "avg-impact",
      label: "Avg Impact Per ASIN",
      value: "$3,160",
      support: "78/82 ASINs measurable",
    },
    {
      id: "actions-taken",
      label: "Actions Taken",
      value: "128",
      support: "Actioned on 82 ASINs",
    },
  ],
  rows: [
    {
      id: "imp-1",
      productName: "KitchenAid Artisan 5-Quart Tilt-Head Stand Mixer KSM150PS",
      asin: "B00005UP2P",
      brand: "KitchenAid",
      thumbnailUrl: "https://placehold.co/64x64/fee2e2/b91c1c?text=KA",
      impactLabel: "+$48,200",
      impactCents: 4820000,
      whatChanged: "Title + bullets optimized for holiday gift intent",
      changedOn: "Sep 4, 2026",
    },
    {
      id: "imp-2",
      productName: "Instant Pot Duo 7-in-1 Electric Pressure Cooker, 6 Qt",
      asin: "B00FLYWNYQ",
      brand: "Instant Pot",
      thumbnailUrl: "https://placehold.co/64x64/f3e8ff/7e22ce?text=IP",
      impactLabel: "+$36,840",
      impactCents: 3684000,
      whatChanged: "Description expanded with recipes and use cases",
      changedOn: "Sep 2, 2026",
    },
    {
      id: "imp-3",
      productName: "Dyson V11 Animal Cordless Vacuum Cleaner with Powerful Suction",
      asin: "B07GR5MSKD",
      brand: "Dyson",
      thumbnailUrl: "https://placehold.co/64x64/dbeafe/1d4ed8?text=DY",
      impactLabel: "+$31,150",
      impactCents: 3115000,
      whatChanged: "AEO title rewrite for “best cordless vacuum” prompts",
      changedOn: "Aug 28, 2026",
    },
    {
      id: "imp-4",
      productName: "Shark Navigator Lift-Away Professional Upright Vacuum NV356E",
      asin: "B003IH3JN4",
      brand: "Shark",
      thumbnailUrl: "https://placehold.co/64x64/e0f2fe/0369a1?text=SH",
      impactLabel: "+$28,960",
      impactCents: 2896000,
      whatChanged: "Bullets rewritten; compliance image set corrected",
      changedOn: "Aug 26, 2026",
    },
    {
      id: "imp-5",
      productName: "Yankee Candle Black Cherry Large Jar Candle, 22 oz",
      asin: "B08NF9KBZ4",
      brand: "Yankee Candle",
      thumbnailUrl: "https://placehold.co/64x64/fce7f3/be185d?text=YC",
      impactLabel: "+$24,310",
      impactCents: 2431000,
      whatChanged: "Seasonal scent keywords added to title and bullets",
      changedOn: "Aug 22, 2026",
    },
    {
      id: "imp-6",
      productName: "Vitamix E310 Explorian Blender, Professional Grade",
      asin: "B079KLGWGR",
      brand: "Vitamix",
      thumbnailUrl: "https://placehold.co/64x64/ecfdf5/065f46?text=VM",
      impactLabel: "+$21,480",
      impactCents: 2148000,
      whatChanged: "Title shortened; PDP now reflects PIM live copy",
      changedOn: "Aug 20, 2026",
    },
    {
      id: "imp-7",
      productName: "Vevor Electric Grain Mill Grinder - High Speed, Commercial Grade",
      asin: "B00H8R3KM2",
      brand: "Vevor",
      thumbnailUrl: "https://placehold.co/64x64/dcfce7/15803d?text=VV",
      impactLabel: "+$18,720",
      impactCents: 1872000,
      whatChanged: "Missing description published; bullets enriched",
      changedOn: "Aug 18, 2026",
    },
    {
      id: "imp-8",
      productName: "iRobot Roomba i3+ EVO Self-Emptying Robot Vacuum",
      asin: "B08C4L7HC1",
      brand: "iRobot",
      thumbnailUrl: "https://placehold.co/64x64/fafafa/374151?text=iR",
      impactLabel: "+$16,540",
      impactCents: 1654000,
      whatChanged: "Image mismatch fixed; title aligned to PDP crawl",
      changedOn: "Aug 15, 2026",
    },
    {
      id: "imp-9",
      productName: "NutriChef Food Processor - 8-Cup Capacity, Digital Control Panel",
      asin: "B00I0DI0Z6",
      brand: "NutriChef",
      thumbnailUrl: "https://placehold.co/64x64/ede9fe/7c3aed?text=NC",
      impactLabel: "+$12,180",
      impactCents: 1218000,
      whatChanged: "PDP-only content staged into PIM and syndicated",
      changedOn: "Aug 14, 2026",
    },
    {
      id: "imp-10",
      productName: "Proctor Silex 2-Slice Toaster with Wide Slots",
      asin: "B00FQK1H8C",
      brand: "Proctor Silex",
      thumbnailUrl: "https://placehold.co/64x64/fef3c7/92400e?text=PS",
      impactLabel: "+$8,100",
      impactCents: 810000,
      whatChanged: "Bullet count raised; feature clarity improved",
      changedOn: "Aug 13, 2026",
    },
  ],
}
