import type { ImpactSummary } from "./types"

/**
 * This-year captured opportunity from the launchpad ($800K, 128 SKUs live).
 * The table is a ranked sample of 6 SKUs — row impacts do not sum to $800K.
 *
 * All rows belong to Aurelle — a trending, Gen Z-focused brand of cozy,
 * eco-friendly candles and home fragrance.
 */
export const impactSummary: ImpactSummary = {
  dateRangeLabel: "Jan 1 – Dec 31, 2026",
  brands: ["All Brands", "Aurelle"],
  metrics: [
    {
      id: "incremental-sales-lift",
      label: "Incremental sales lift",
      value: "$800K",
      valueTone: "success",
      support: "128 SKUs live · table is a 6-SKU sample, not this total",
    },
    {
      id: "conversion-rate-lift",
      label: "Conversion rate lift",
      value: "3.0%",
      support: "Median pilot lift, 42 SKUs",
    },
    {
      id: "ai-visibility-lift",
      label: "AI visibility lift",
      value: "8.4%",
      support: "Alexa AI chip citations",
    },
    {
      id: "time-saved",
      label: "Time saved",
      value: "61.9 hrs",
      support: "128 SKUs · 29 min saved each",
    },
  ],
  rows: [
    {
      id: "imp-1",
      productName: "Aurelle Vegan Soy Candle, Golden Hour, 8oz",
      asin: "B0D8QXK4TN",
      brand: "Aurelle",
      category: "Home Fragrance · Candles",
      thumbnailUrl: "/images/aurelle/soy-candle-golden-hour.jpg",
      impactLabel: "+$80K",
      impactCents: 8000000,
      attributionApproach: "A/B test",
      whatChanged: "Title",
      changedOn: "Nov 20, 2026",
    },
    {
      id: "imp-2",
      productName: "Aurelle Reed Diffuser, Cashmere Fog, 4oz",
      asin: "B0AURELLE02",
      brand: "Aurelle",
      category: "Home Fragrance · Diffusers",
      thumbnailUrl: "/images/aurelle/reed-diffuser-cashmere-fog.jpg",
      impactLabel: "+$62K",
      impactCents: 6200000,
      attributionApproach: "A/B test",
      whatChanged: "Title",
      changedOn: "Oct 1, 2025",
    },
    {
      id: "imp-3",
      productName: "Aurelle Travel Tin Candle, Campfire Nights, 4oz",
      asin: "B0AURELLE03",
      brand: "Aurelle",
      category: "Home Fragrance · Candles",
      thumbnailUrl: "/images/aurelle/travel-tin-candle.jpg",
      impactLabel: "+$48K",
      impactCents: 4800000,
      attributionApproach: "A/B test",
      whatChanged: "Bullet Points",
      changedOn: "Jul 1, 2026",
    },
    {
      id: "imp-4",
      productName: "Aurelle Wax Melt Sampler, Cozy Nights, 6-Pack",
      asin: "B0AURELLE04",
      brand: "Aurelle",
      category: "Home Fragrance · Wax Melts",
      thumbnailUrl: "/images/aurelle/wax-melt-sampler.jpg",
      impactLabel: "+$35K",
      impactCents: 3500000,
      attributionApproach: "A/B test",
      whatChanged: "Title, Bullet Points",
      changedOn: "Feb 10, 2026",
    },
    {
      id: "imp-5",
      productName: "Aurelle Soy Candle Trio Gift Set, Golden Hour",
      asin: "B0AURELLE05",
      brand: "Aurelle",
      category: "Home Fragrance · Gift Sets",
      thumbnailUrl: "/images/aurelle/soy-candle-trio-gift-set.jpg",
      impactLabel: "+$28K",
      impactCents: 2800000,
      attributionApproach: "A/B test",
      whatChanged: "Title, Bullet Points",
      changedOn: "Apr 1, 2026",
    },
    {
      id: "imp-6",
      productName: "Aurelle Ceramic Wax Melt Warmer",
      asin: "B0AURELLE06",
      brand: "Aurelle",
      category: "Home Fragrance · Warmers",
      thumbnailUrl: "/images/aurelle/travel-tin-candle.jpg",
      impactLabel: "+$19K",
      impactCents: 1900000,
      attributionApproach: "Modelled",
      whatChanged: "Title, Bullet Points",
      changedOn: "May 3, 2026",
    },
  ],
}
