import { candleThumbnail } from "@/lib/candle-thumbnails"
import type { ImpactSummary } from "./types"

/**
 * Period slice of launchpad “captured” opportunity ($1.84M YTD).
 * Numbers are sized so table impacts roughly reconcile to Incremental Sales.
 */
export const impactSummary: ImpactSummary = {
  dateRangeLabel: "Aug 13 - Sep 11, 2026",
  brands: [
    "All Brands",
    "Aurelle Candles",
  ],
  metrics: [
    {
      id: "incremental-sales",
      label: "Incremental Sales",
      value: "$246,480",
      valueTone: "success",
      supportLead: "+18%",
      support: "vs prior period",
    },
    {
      id: "incremental-units",
      label: "Incremental Units Sold",
      value: "4,820",
      support: "Across measurable events",
    },
    {
      id: "avg-impact",
      label: "Avg Impact Per ASIN",
      value: "$3,160",
      support: "78/82 ASINs measurable",
    },
    {
      id: "actions-taken",
      label: "Actions Taken",
      value: "128",
      support: "Actioned on 82 ASINs",
    },
  ],
  rows: [
    {
      id: "imp-1",
      productName: "Aurelle Candles Bergamot Grove Pillar Set",
      asin: "B00005UP2P",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B00005UP2P"),
      impactLabel: "+$48,200",
      impactCents: 4820000,
      whatChanged: "Title + bullets optimized for holiday gift intent",
      changedOn: "Sep 4, 2026",
    },
    {
      id: "imp-2",
      productName: "Aurelle Candles Coastal Linen Large Jar, 22 oz",
      asin: "B00FLYWNYQ",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B00FLYWNYQ"),
      impactLabel: "+$36,840",
      impactCents: 3684000,
      whatChanged: "Description expanded with scent notes and burn time",
      changedOn: "Sep 2, 2026",
    },
    {
      id: "imp-3",
      productName: "Aurelle Candles Amber Floral Soy Candle, 16 oz",
      asin: "B07GR5MSKD",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B07GR5MSKD"),
      impactLabel: "+$31,150",
      impactCents: 3115000,
      whatChanged: "AEO title rewrite for “best soy candle” prompts",
      changedOn: "Aug 28, 2026",
    },
    {
      id: "imp-4",
      productName: "Aurelle Candles Pink Sands Tumbler, 10 oz",
      asin: "B003IH3JN4",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B003IH3JN4"),
      impactLabel: "+$28,960",
      impactCents: 2896000,
      whatChanged: "Bullets rewritten; compliance image set corrected",
      changedOn: "Aug 26, 2026",
    },
    {
      id: "imp-5",
      productName: "Aurelle Candles Noir Cherry Large Jar, 22 oz",
      asin: "B08NF9KBZ4",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B08NF9KBZ4"),
      impactLabel: "+$24,310",
      impactCents: 2431000,
      whatChanged: "Seasonal scent keywords added to title and bullets",
      changedOn: "Aug 22, 2026",
    },
    {
      id: "imp-6",
      productName: "Aurelle Candles Hearthwood Cedar Jar, 18 oz",
      asin: "B079KLGWGR",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B079KLGWGR"),
      impactLabel: "+$21,480",
      impactCents: 2148000,
      whatChanged: "Title shortened; PDP now reflects PIM live copy",
      changedOn: "Aug 20, 2026",
    },
    {
      id: "imp-7",
      productName: "Aurelle Candles Spiced Cedar 3-Wick, 21 oz",
      asin: "B00H8R3KM2",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B00H8R3KM2"),
      impactLabel: "+$18,720",
      impactCents: 1872000,
      whatChanged: "Missing description published; bullets enriched",
      changedOn: "Aug 18, 2026",
    },
    {
      id: "imp-8",
      productName: "Aurelle Candles Rasa Decorative Candle Duo",
      asin: "B08C4L7HC1",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B08C4L7HC1"),
      impactLabel: "+$16,540",
      impactCents: 1654000,
      whatChanged: "Image mismatch fixed; title aligned to PDP crawl",
      changedOn: "Aug 15, 2026",
    },
    {
      id: "imp-9",
      productName: "Aurelle Candles Citrus Zest Soy Jar, 14 oz",
      asin: "B00I0DI0Z6",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B00I0DI0Z6"),
      impactLabel: "+$12,180",
      impactCents: 1218000,
      whatChanged: "PDP-only content staged into PIM and syndicated",
      changedOn: "Aug 14, 2026",
    },
    {
      id: "imp-10",
      productName: "Aurelle Candles Vanilla Tobacco Jar, 12 oz",
      asin: "B00FQK1H8C",
      brand: "Aurelle Candles",
      thumbnailUrl: candleThumbnail("B00FQK1H8C"),
      impactLabel: "+$8,100",
      impactCents: 810000,
      whatChanged: "Bullet count raised; feature clarity improved",
      changedOn: "Aug 13, 2026",
    },
  ],
}
