import type { OverviewSnapshot } from "../overview-for-range"

export const lastYearOverview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 3.4,
    realizedMillions: 2.15,
    periodLabel: "Jan 1 – Dec 31, 2025",
    pvpDelta: "+$620K PvP",
    pvpDeltaPositive: true,
  },
  capturedSplit: {
    retailReadinessMillions: 0.25,
    amazonOptimizationMillions: 1.15,
    seasonalMillions: 0.75,
  },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$2.15M",
      millions: 2.15,
      tooltip:
        "Opportunity realized in 2025 — content changes went live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$900K",
      millions: 0.9,
      tooltip:
        "Holiday 2025 window that closed before the remaining SKUs were published.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$350K",
      millions: 0.35,
      tooltip:
        "Always-on SEO and AEO lifts still open at the end of 2025.",
    },
    {
      id: "expired",
      label: "Lost",
      amountLabel: "$720K",
      millions: 0.72,
      muted: true,
      tooltip:
        "Prime Day 2025. 164 deal SKUs still had gaps when the window closed — excluded from the 2025 active total.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Annualized opportunity",
      heading: "2025 opportunity",
      periodBadge: "Jan 1 – Dec 31, 2025",
      heroAmountLabel: "$3.40M",
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$0.20M",
      amazonOptimizationLiftLabel: "Amazon optimization opportunity",
      amazonOptimizationLiftAmount: "$0.90M",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$2.30M",
      liftBarPct: { retailReadiness: 6, amazonOptimization: 26, seasonal: 68 },
      kpis: [
        { value: "36", label: "SKUs A/B tested in 2025" },
        { value: "+2.7%", label: "Median sales lift" },
        { value: "28 of 36", label: "Challenger won" },
      ],
      calcRows: [
        {
          label: "2025 revenue on attribute-blocked SKUs",
          value: "$6.67M",
        },
        { label: "× banked lift rate", value: "3.0%" },
        {
          label: "Retail readiness opportunity",
          value: "$0.20M",
          variant: "subtotal",
        },
        {
          label: "2025 revenue on always-on SEO & AEO gaps",
          value: "$30.00M",
        },
        { label: "× banked lift rate", value: "3.0%" },
        {
          label: "Amazon optimization opportunity",
          value: "$0.90M",
          variant: "subtotal",
        },
        {
          label: "2025 revenue in the 2 weeks after each seasonal event",
          value: "$76.67M",
        },
        { label: "× banked lift rate", value: "3.0%" },
        {
          label: "Seasonal opportunity",
          value: "$2.30M",
          variant: "subtotal",
        },
      ],
      calcSummary: {
        label: "Opportunity in 2025",
        value: "$3.40M",
        variant: "total",
      },
      methodology:
        "2025 revenue comes from Vendor Central history for the full calendar year. $6.67M × 3.0% = $0.20M. $30.00M × 3.0% = $0.90M. $76.67M × 3.0% = $2.30M. Together that is $3.40M. The missed $720K Prime Day window is excluded.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value Realized",
      heading: "Value realized",
      periodBadge: "Jan 1 – Dec 31, 2025",
      trendBadge: { label: "+$210K in Q4", positive: true },
      heroAmountLabel: "$2.15M",
      heroBordered: true,
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$250K",
      amazonOptimizationLiftLabel: "Amazon optimization opportunity",
      amazonOptimizationLiftAmount: "$1.15M",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$750K",
      liftBarPct: { retailReadiness: 12, amazonOptimization: 53, seasonal: 35 },
      kpis: [
        { value: "96", label: "SKUs live" },
        { value: "4.1 days", label: "Median approve-to-live" },
        { value: "2025", label: "Closed year" },
      ],
      calcRows: [],
      bodyCopy:
        "Counts only the 96 SKUs published in 2025, accrued over the days their content was actually live — not recommendations that stayed in the queue when the year closed.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      unrealized: {
        title: "Identified but never published",
        amountLabel: "$720K",
        description:
          "Prime Day, Jul 2025. 164 deal SKUs still had title and bullet gaps when the window closed. Not part of the $3.40M above and not recoverable.",
      },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#4",
      delta: "▲ 1 place vs year-end prior week",
      deltaPositive: true,
      live: true,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "15" },
          { label: "Median position when cited", value: "#4" },
        ],
        summaryRow: { label: "Prior week, Dec 2025", value: "#5" },
        methodology:
          "Standing at the end of 2025, not this year's median. Prompts where you don't appear are excluded from the median.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "24.6%",
      delta: "▲ 1.5 pp vs prior week",
      deltaPositive: true,
      live: true,
      footnote: "Weighted, up from 23.1% the week before year-end",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Your weighted share at year-end 2025", value: "24.6%" },
          { label: "Prior week", value: "23.1%" },
          { label: "Closest competitor", value: "46%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Share of brand citations in the last 2025 prompt run, weighted by position. 24.6% − 23.1% = 1.5 percentage points.",
      },
    },
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "5.8",
      delta: "4% productivity boost vs prior year",
      deltaPositive: true,
      footnote: "96 actions taken · 46.4 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published in 2025", value: "96" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
          { label: "Total saved", value: "46.4 hrs" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "5.8 days" },
        methodology:
          "Time saved counts only SKUs published in 2025. 96 SKUs × 29 minutes = 46.4 hours, or 5.8 working days.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "holiday-2025",
        name: "Holiday 2025",
        valueLabel: "$900K",
        publishBy: "Nov 12",
        skuCount: 210,
        goesLiveNote: "window closed",
      },
    ],
  },
  streams: [
    {
      id: "seasonal",
      title: "Seasonal opportunity",
      context: "Holiday 2025 · Publish by Nov 12 ·",
      contextHighlight: "window closed",
      skuCount: 210,
      valueLabel: "$900K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**210 SKUs** were missing gift framing, occasion keywords, or bundle language for **Holiday 2025**. Ranked by revenue, the **top 20** carried about **a third of the $900K**.",
      remainingLabel: "204 more SKUs worth $671K, ranked by impact.",
      buckets: [
        {
          id: "ly-sea-1",
          title: "No holiday keyword in title",
          skuCount: 72,
          fillTime: "~3 min",
          valueThousands: 300,
          alsoNote: "Publish by Nov 12 · 44 also needed gift notes in bullets",
          outcome: "captured",
        },
        {
          id: "ly-sea-2",
          title: "Bullets don't mention gifting",
          skuCount: 52,
          fillTime: "~2 min",
          valueThousands: 220,
          alsoNote: "Holiday window · 31 also missing urgency language",
          outcome: "captured",
        },
        {
          id: "ly-sea-3",
          title: "Gift-set contents not listed",
          skuCount: 38,
          fillTime: "~2 min",
          valueThousands: 170,
          alsoNote: "Gift sets · 22 also missing a holiday keyword",
        },
        {
          id: "ly-sea-4",
          title: "Blocked — attributes missing first",
          skuCount: 28,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 120,
          alsoNote: "Seasonal copy could not publish until attributes were backfilled",
        },
        {
          id: "ly-sea-5",
          title: "No holiday urgency language",
          skuCount: 20,
          fillTime: "~2 min",
          valueThousands: 90,
          alsoNote: "16 also had thin bullets",
        },
      ],
      rows: [
        {
          id: "ly-sea-r1",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "No holiday keyword in title",
          impactThousands: 68,
        },
        {
          id: "ly-sea-r2",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "Bullets don't mention gifting",
          impactThousands: 52,
        },
        {
          id: "ly-sea-r3",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Gift-set contents not listed",
          impactThousands: 40,
        },
        {
          id: "ly-sea-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "No holiday urgency language",
          impactThousands: 31,
        },
        {
          id: "ly-sea-r5",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Title truncated before the occasion",
          impactThousands: 22,
        },
        {
          id: "ly-sea-r6",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Bullets 4 and 5 empty",
          impactThousands: 16,
        },
      ],
    },
    {
      id: "retail-readiness",
      title: "Retail readiness opportunity",
      context: "Vendor Central Attribute Gaps",
      skuCount: 188,
      valueLabel: "$246K",
      valueKind: "blocked",
      tone: "default",
      insight:
        "**188 SKUs** were missing required **Amazon attributes** at the end of 2025. Amazon would not accept a content push until these were backfilled, so **$246K** of **PDP fixes** stayed stuck behind this.",
      remainingLabel: "184 more SKUs, $203K blocked in total.",
      buckets: [
        {
          id: "ly-rr-mandatory",
          title: "Agent-drafted, ready for approval",
          skuCount: 58,
          fillTime: "~1 min each",
          valueThousands: 82,
          badge: "Approval required",
          alsoNote:
            "These SKUs are not syndicatable. Make your catalog retail ready and unblock syndication.",
          outcome: "captured",
        },
        {
          id: "ly-rr-recommended",
          title: "Missing mandatory attributes",
          skuCount: 130,
          fillMode: "input",
          fillTime: "~1-2 min each",
          valueThousands: 164,
          badge: "Input required",
          alsoNote:
            "This will improve search and answer engine citation rate.",
        },
      ],
      rows: [
        {
          id: "ly-rr-r1",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "Unit price missing on the 2025 year-end feed",
          impactThousands: 18,
        },
        {
          id: "ly-rr-r2",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Item weight missing",
          impactThousands: 12,
        },
        {
          id: "ly-rr-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Safety sheet not attached",
          impactThousands: 8,
        },
        {
          id: "ly-rr-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Country of origin blank",
          impactThousands: 5,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always-on optimization opportunity",
      context: "2025 · SEO & AEO · No deadline",
      skuCount: 240,
      valueLabel: "$620K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**240 SKUs** still open at year-end 2025 were missing category keywords or the structured specs an **AI answer engine** needs to cite the listing.",
      remainingLabel: "235 more SKUs worth $453K, ranked by impact.",
      buckets: [
        {
          id: "ly-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 84,
          fillTime: "~2 min",
          valueThousands: 220,
          alsoNote: "SEO lift · 51 also missing a search term in the title",
        },
        {
          id: "ly-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 62,
          fillTime: "~3 min",
          valueThousands: 160,
          alsoNote: "AEO lift · 37 also had thin comparison bullets",
        },
        {
          id: "ly-pdp-3",
          title: "Title missing key search term",
          skuCount: 44,
          fillTime: "~2 min",
          valueThousands: 110,
          alsoNote: "Always on · 26 overlap with missing category keywords",
        },
        {
          id: "ly-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 30,
          fillTime: "~2 min",
          valueThousands: 80,
          alsoNote: "AEO lift · 18 also missing answer-ready specs",
        },
        {
          id: "ly-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 20,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 50,
          alsoNote: "SEO copy could not publish until attributes were backfilled",
        },
      ],
      rows: [
        {
          id: "ly-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing top category keywords in bullets",
          impactThousands: 54,
          findingType: "SEO",
        },
        {
          id: "ly-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready specs for year-end prompts",
          impactThousands: 41,
          findingType: "AEO",
        },
        {
          id: "ly-pdp-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Title missing 'soy jar'",
          impactThousands: 32,
          findingType: "SEO",
        },
        {
          id: "ly-pdp-r4",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 24,
          findingType: "AEO",
        },
        {
          id: "ly-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 16,
          findingType: "SEO",
        },
      ],
    },
  ],
}
