import type { OverviewSnapshot } from "../overview-for-range"

export const q1Overview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 0.21,
    realizedMillions: 0.15,
    periodLabel: "Jan 1 – Mar 31, 2026",
    title: "Q1 content opportunity",
    pvpDelta: "First quarter tracked this year",
    pvpDeltaPositive: false,
  },
  streamsTitle: "Q1 opportunity streams",
  streamsDescription:
    "The opportunity in each stream, and how we performed against it.",
  capturedSplit: {
    retailReadinessMillions: 0.02,
    amazonOptimizationMillions: 0.09,
    seasonalMillions: 0.04,
  },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$150K",
      millions: 0.15,
      tooltip:
        "Opportunity already realized in Q1 — content changes are live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$16K",
      millions: 0.016,
      tooltip:
        "Valentine's Day window closed Jan 26. $16K lost to inaction is gone for the year.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$44K",
      millions: 0.044,
      tooltip:
        "Always-on and retail-readiness dollars not captured in Q1 — rolled into Q2 rather than expiring.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Opportunity by stream",
      heading: "Q1 opportunity, by stream",
      periodBadge: "Jan 1 – Mar 31, 2026",
      heroAmountLabel: "$210K",
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$28K",
      amazonOptimizationLiftLabel: "Always-on optimization opportunity",
      amazonOptimizationLiftAmount: "$126K",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$56K",
      liftBarPct: { retailReadiness: 13, amazonOptimization: 60, seasonal: 27 },
      kpis: [],
      calcRows: [],
      calcSummary: { label: "Opportunity in Q1", value: "$210K", variant: "total" },
      methodology:
        "Seasonal loss is permanent — the window closed. Always-on and Retail readiness have no deadline, so what wasn't captured this quarter rolled into Q2's queue rather than expiring.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value realized",
      heading: "Value realized",
      periodBadge: "Jan 1 – Mar 31, 2026",
      heroAmountLabel: "$150K",
      heroBordered: true,
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$20K",
      amazonOptimizationLiftLabel: "Always-on optimization opportunity",
      amazonOptimizationLiftAmount: "$90K",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$40K",
      liftBarPct: { retailReadiness: 13, amazonOptimization: 60, seasonal: 27 },
      kpis: [
        { value: "31", label: "SKUs published in Q1" },
        { value: "1.9 days", label: "Working days saved" },
        { value: "Q1", label: "First quarter tracked" },
      ],
      calcRows: [],
      bodyCopy:
        "Captured $40K seasonal, $90K always-on, and $20K retail readiness in Q1. The $60K not captured shows as lost on the meter — seasonal is gone; always-on and retail readiness rolled into Q2.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "1.9",
      delta: "First quarter tracked",
      deltaPositive: false,
      footnote: "31 actions taken · 15.0 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published, Q1", value: "31" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "1.9 days" },
        methodology:
          "Only published SKUs count, not ones waiting in the queue. 30 min is the full manual cycle — pull, research, draft, reload. 31 × 29 minutes = 15.0 hours, or 1.9 working days.",
      },
    },
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#5",
      delta: "First quarter tracked",
      deltaPositive: false,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "14" },
          { label: "Median position when cited", value: "#5" },
        ],
        methodology:
          "Median position where cited by Alexa AI, averaged across the quarter. This is the earliest quarter tracked, so there is no prior quarter to compare against.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "29.8%",
      delta: "First quarter tracked",
      deltaPositive: false,
      footnote: "Weighted, closest competitor at 44%",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Q1 weighted share", value: "29.8%" },
          { label: "Closest competitor, Q1", value: "44%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Weighted brand citation share across tracked prompts, averaged across the quarter. This is the earliest quarter tracked, so there is no prior quarter to compare against.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "vday",
        name: "Valentine's Day",
        valueLabel: "$56K",
        publishBy: "Jan 26",
        skuCount: 52,
        goesLiveNote: "window closed",
      },
    ],
  },
  streams: [
    {
      id: "seasonal",
      title: "Seasonal opportunity",
      titleTooltip:
        "Optimizes content ahead of shopping events like Valentine's Day, Mother's Day, and Black Friday.",
      context: "Valentine's Day · Publish by Jan 26 ·",
      contextHighlight: "window closed",
      skuCount: 52,
      valueLabel: "$56K",
      valueKind: "potential",
      tone: "default",
      insight:
        "The window closed on Jan 26. Captured **$40K**; **$16K** lost to inaction is gone for the year — it does not come back.",
      remainingLabel: "46 more SKUs worth $32K, ranked by impact.",
      buckets: [
        {
          id: "q1-sea-1",
          title: "No occasion keyword in title",
          skuCount: 21,
          fillTime: "~3 min",
          valueThousands: 24,
          alsoNote: "Publish by Jan 26 · 12 also need gift notes in bullets",
          outcome: "captured",
        },
        {
          id: "q1-sea-2",
          title: "Bullets don't mention gifting",
          skuCount: 13,
          fillTime: "~2 min",
          valueThousands: 16,
          alsoNote: "Valentine's window · 8 also missing a pair-with scent",
          outcome: "captured",
        },
        {
          id: "q1-sea-3",
          title: "Gift-set contents not listed",
          skuCount: 10,
          fillTime: "~2 min",
          valueThousands: 8,
          alsoNote: "Duo sets · 6 also missing an occasion keyword",
          outcome: "missed",
        },
        {
          id: "q1-sea-4",
          title: "Blocked — attributes missing first",
          skuCount: 5,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 5,
          alsoNote: "Seasonal copy can't publish until attributes are backfilled",
          outcome: "missed",
        },
        {
          id: "q1-sea-5",
          title: "No romantic scent framing",
          skuCount: 3,
          fillTime: "~2 min",
          valueThousands: 3,
          alsoNote: "Floral jars · 2 also have thin bullets",
          outcome: "missed",
        },
      ],
      rows: [
        {
          id: "q1-sea-r1",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "No Valentine's keyword in title",
          impactThousands: 8,
        },
        {
          id: "q1-sea-r2",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Bullets don't mention gifting",
          impactThousands: 6,
        },
        {
          id: "q1-sea-r3",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Gift-set contents not listed",
          impactThousands: 4,
        },
        {
          id: "q1-sea-r4",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "No romantic scent framing",
          impactThousands: 3,
        },
        {
          id: "q1-sea-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Title truncated before the occasion",
          impactThousands: 2,
        },
        {
          id: "q1-sea-r6",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Bullets 4 and 5 empty",
          impactThousands: 1,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always-on optimization opportunity",
      titleTooltip:
        "Keeps listings aligned with brand and retailer guidelines as category trends shift.",
      context: "Always on · SEO and AEO · No deadline",
      skuCount: 98,
      valueLabel: "$126K",
      valueKind: "potential",
      tone: "default",
      insight:
        "No deadline on this stream. Captured **$90K** in Q1; the **$36K** not yet captured rolled into Q2's queue — it is not lost.",
      remainingLabel: "93 more SKUs worth $72K, ranked by impact.",
      buckets: [
        {
          id: "q1-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 36,
          fillTime: "~2 min",
          valueThousands: 48,
          alsoNote: "SEO lift · 22 also missing a search term in the title",
          outcome: "captured",
        },
        {
          id: "q1-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 24,
          fillTime: "~3 min",
          valueThousands: 42,
          alsoNote: "AEO lift · 15 also have thin comparison bullets",
          outcome: "captured",
        },
        {
          id: "q1-pdp-3",
          title: "Title missing key search term",
          skuCount: 18,
          fillTime: "~2 min",
          valueThousands: 18,
          alsoNote: "Always on · 12 overlap with missing category keywords",
        },
        {
          id: "q1-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 14,
          fillTime: "~2 min",
          valueThousands: 12,
          alsoNote: "AEO lift · 9 also missing answer-ready specs",
        },
        {
          id: "q1-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 6,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 6,
          alsoNote: "SEO copy can't publish until attributes are backfilled",
        },
      ],
      rows: [
        {
          id: "q1-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing soy-candle keyword in bullets",
          impactThousands: 18,
          findingType: "SEO",
        },
        {
          id: "q1-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready burn-time spec",
          impactThousands: 14,
          findingType: "AEO",
        },
        {
          id: "q1-pdp-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Title missing 'soy jar'",
          impactThousands: 10,
          findingType: "SEO",
        },
        {
          id: "q1-pdp-r4",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 8,
          findingType: "AEO",
        },
        {
          id: "q1-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 5,
          findingType: "SEO",
        },
      ],
    },
    {
      id: "retail-readiness",
      title: "Retail readiness opportunity",
      titleTooltip:
        "Cleans up backend catalog data so SKUs meet retailer syndication requirements.",
      context: "Vendor Central attribute gaps · No deadline",
      skuCount: 34,
      valueLabel: "$28K",
      valueKind: "blocked",
      tone: "default",
      insight:
        "No deadline on this stream. Captured **$20K** in Q1; the **$8K** not yet captured rolled into Q2's queue — it is not lost.",
      remainingLabel: "30 more SKUs, $18K blocked in total.",
      buckets: [
        {
          id: "q1-rr-mandatory",
          title: "Agent-drafted, ready for approval",
          skuCount: 14,
          fillTime: "~1 min each",
          valueThousands: 20,
          badge: "Approval required",
          alsoNote:
            "These SKUs are not syndicatable. Make your catalog retail ready and unblock syndication.",
          outcome: "captured",
        },
        {
          id: "q1-rr-recommended",
          title: "Missing mandatory attributes",
          skuCount: 20,
          fillMode: "input",
          fillTime: "~1-2 min each",
          valueThousands: 8,
          badge: "Input required",
          alsoNote:
            "This will improve search and answer engine citation rate.",
        },
      ],
      rows: [
        {
          id: "q1-rr-r1",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "Unit price missing on the Q1 feed",
          impactThousands: 4,
        },
        {
          id: "q1-rr-r2",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Item weight missing",
          impactThousands: 3,
        },
        {
          id: "q1-rr-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Safety sheet not attached",
          impactThousands: 2,
        },
        {
          id: "q1-rr-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Country of origin blank",
          impactThousands: 1,
        },
      ],
    },
  ],
}
