import type { OverviewSnapshot } from "../overview-for-range"

export const q1Overview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 0.53,
    realizedMillions: 0.1,
    periodLabel: "Jan 1 – Mar 31, 2026",
  },
  capturedSplit: { foundationalMillions: 0.07, seasonalMillions: 0.03 },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$100K",
      millions: 0.1,
      tooltip:
        "Opportunity already realized in Q1 — content changes are live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$380K",
      millions: 0.38,
      tooltip:
        "Valentine's Day window. Publish by Feb 1 to capture the lift before the moment passes.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$50K",
      millions: 0.05,
      tooltip:
        "Always-on SEO and AEO lifts identified in Q1, with no hard event deadline.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Annualized opportunity",
      heading: "Q1 opportunity",
      periodBadge: "Jan 1 – Mar 31, 2026",
      heroAmountLabel: "$0.53M",
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$0.15M",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$0.38M",
      liftBarPct: { foundational: 28, seasonal: 72 },
      kpis: [
        { value: "8", label: "SKUs A/B tested in Q1" },
        { value: "+2.8%", label: "Median sales lift" },
        { value: "6 of 8", label: "Challenger won" },
      ],
      calcRows: [
        { label: "Revenue, SKUs not yet optimized in Q1", value: "$5.00M" },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Foundational lift", value: "$0.15M", variant: "subtotal" },
        {
          label: "Revenue in the 2 weeks around Valentine's Day",
          value: "$12.67M",
        },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Seasonal lift", value: "$0.38M", variant: "subtotal" },
      ],
      calcSummary: { label: "Opportunity in Q1", value: "$0.53M", variant: "total" },
      methodology:
        "Q1 revenue comes from Vendor Central history for Jan 1 – Mar 31. The 3.0% rate is the same pilot baseline used for the year, applied only to revenue in this window.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value Realized",
      heading: "Value realized",
      periodBadge: "Jan 1 – Mar 31, 2026",
      trendBadge: { label: "+$40K vs prior month", positive: true },
      heroAmountLabel: "$100K",
      heroBordered: true,
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$70K",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$30K",
      liftBarPct: { foundational: 70, seasonal: 30 },
      kpis: [
        { value: "30", label: "SKUs live" },
        { value: "2.4 days", label: "Median approve-to-live" },
        { value: "Q1", label: "Accruing this quarter" },
      ],
      calcRows: [],
      bodyCopy:
        "Counts only the 30 SKUs published in Q1, accrued over the days their content was actually live in the Jan 1 – Mar 31 window — not the full-year value of those tests.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "1.8",
      delta: "6% productivity boost WoW",
      deltaPositive: true,
      footnote: "30 actions taken · 14.5 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published in Q1", value: "30" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
          { label: "Total saved", value: "14.5 hrs" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "1.8 days" },
        methodology:
          "Time saved counts only SKUs published in this quarter. 30 SKUs × 29 minutes = 14.5 hours, or 1.8 working days.",
      },
    },
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#5",
      delta: "▲ 1 place vs prior week",
      deltaPositive: true,
      live: true,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "14" },
          { label: "Median position when cited", value: "#5" },
        ],
        summaryRow: { label: "Prior week in Q1", value: "#6" },
        methodology:
          "Standing at the end of Q1, not the full-year median. Prompts where you don't appear are excluded from the median.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "28.4%",
      delta: "▲ 1.5 pp WoW",
      deltaPositive: true,
      live: true,
      footnote: "Weighted, up from 26.9% the week before",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Your weighted share in Q1", value: "28.4%" },
          { label: "Prior week", value: "26.9%" },
          { label: "Closest competitor", value: "44%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Share of brand citations in the Q1 prompt runs, weighted by position. 28.4% − 26.9% = 1.5 percentage points.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "vday",
        name: "Valentine's Day",
        valueLabel: "$380K",
        publishBy: "Feb 1",
        skuCount: 96,
        goesLiveNote: "window closed",
      },
    ],
  },
  retrospective: {
    heading: "Q1 recap",
    highlights: [
      {
        id: "q1-h1",
        title: "Valentine's copy live on the top 24 SKUs",
        amountLabel: "$30K",
      },
      {
        id: "q1-h2",
        title: "Unit price backfilled on 22 SKUs",
        amountLabel: "$28K",
      },
    ],
    lowlights: [
      {
        id: "q1-l1",
        title: "72 Valentine's SKUs never published",
        amountLabel: "$350K",
      },
    ],
  },
  streams: [
    {
      id: "retail-readiness",
      title: "Retail-readiness",
      context: "of catalog is retail-ready",
      skuCount: 64,
      valueLabel: "$86K",
      valueKind: "blocked",
      tone: "warning",
      readyPercent: 97,
      insight:
        "**64 SKUs** are missing required **Amazon attributes** in the Q1 catalog pull — unit price, weight, or origin. Amazon won’t accept a content push until these are backfilled, so **$86K** of **PDP fixes** queued in this quarter are stuck behind this.",
      remainingLabel: "60 more SKUs, $67K blocked in total.",
      buckets: [
        {
          id: "q1-rr-1",
          title: "Unit price missing",
          skuCount: 22,
          fillTime: "~1 min",
          valueThousands: 28,
          releasesThousands: 6,
          alsoNote: "18 also have thin Valentine's bullets",
          outcome: "captured",
        },
        {
          id: "q1-rr-2",
          title: "Item weight missing",
          skuCount: 16,
          fillTime: "~1 min",
          valueThousands: 22,
          releasesThousands: 4,
          alsoNote: "12 also missing burn-time specs",
        },
        {
          id: "q1-rr-3",
          title: "Safety & compliance docs missing",
          skuCount: 12,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 16,
          releasesThousands: 3,
          alsoNote: "9 also have title gaps",
        },
        {
          id: "q1-rr-4",
          title: "Material composition missing",
          skuCount: 8,
          fillTime: "~1 min",
          valueThousands: 12,
          releasesThousands: 2,
          alsoNote: "6 also have thin bullets",
        },
        {
          id: "q1-rr-5",
          title: "Country of origin missing",
          skuCount: 6,
          fillTime: "~1 min",
          valueThousands: 8,
          releasesThousands: 1,
          alsoNote: "4 also have title gaps",
        },
      ],
      rows: [
        {
          id: "q1-rr-r1",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "Unit price missing on the Q1 feed",
          impactThousands: 8,
        },
        {
          id: "q1-rr-r2",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Item weight missing",
          impactThousands: 5,
        },
        {
          id: "q1-rr-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Safety sheet not attached",
          impactThousands: 4,
        },
        {
          id: "q1-rr-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Country of origin blank",
          impactThousands: 2,
        },
      ],
    },
    {
      id: "seasonal",
      title: "Seasonal",
      context: "Valentine's Day · Publish by Feb 1 ·",
      contextHighlight: "window closed",
      skuCount: 96,
      valueLabel: "$380K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**96 SKUs** are missing gifting language, occasion keywords, or pair-with notes for **Valentine's Day**. Ranked by revenue each fix is worth, the **top 20** carry about **a third of the $380K**.",
      remainingLabel: "90 more SKUs worth $218K, ranked by impact.",
      buckets: [
        {
          id: "q1-sea-1",
          title: "No occasion keyword in title",
          skuCount: 38,
          fillTime: "~3 min",
          valueThousands: 140,
          alsoNote: "Publish by Feb 1 · 22 also need gift notes in bullets",
          outcome: "captured",
        },
        {
          id: "q1-sea-2",
          title: "Bullets don't mention gifting",
          skuCount: 24,
          fillTime: "~2 min",
          valueThousands: 90,
          alsoNote: "Valentine's window · 14 also missing a pair-with scent",
        },
        {
          id: "q1-sea-3",
          title: "Gift-set contents not listed",
          skuCount: 18,
          fillTime: "~2 min",
          valueThousands: 70,
          alsoNote: "Duo sets · 11 also missing an occasion keyword",
        },
        {
          id: "q1-sea-4",
          title: "Blocked — attributes missing first",
          skuCount: 10,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 48,
          alsoNote: "Seasonal copy can't publish until attributes are backfilled",
        },
        {
          id: "q1-sea-5",
          title: "No romantic scent framing",
          skuCount: 6,
          fillTime: "~2 min",
          valueThousands: 32,
          alsoNote: "Floral jars · 4 also have thin bullets",
        },
      ],
      rows: [
        {
          id: "q1-sea-r1",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "No Valentine's keyword in title",
          impactThousands: 48,
        },
        {
          id: "q1-sea-r2",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Bullets don't mention gifting",
          impactThousands: 36,
        },
        {
          id: "q1-sea-r3",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Gift-set contents not listed",
          impactThousands: 28,
        },
        {
          id: "q1-sea-r4",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "No romantic scent framing",
          impactThousands: 22,
        },
        {
          id: "q1-sea-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Title truncated before the occasion",
          impactThousands: 16,
        },
        {
          id: "q1-sea-r6",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Bullets 4 and 5 empty",
          impactThousands: 12,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always on optimization",
      context: "Q1 · SEO & AEO · No deadline",
      skuCount: 88,
      valueLabel: "$210K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**88 SKUs** identified in Q1 are missing category keywords or the structured specs an **AI answer engine** needs to cite the listing.",
      remainingLabel: "83 more SKUs worth $118K, ranked by impact.",
      buckets: [
        {
          id: "q1-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 32,
          fillTime: "~2 min",
          valueThousands: 80,
          alsoNote: "SEO lift · 20 also missing a search term in the title",
        },
        {
          id: "q1-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 22,
          fillTime: "~3 min",
          valueThousands: 52,
          alsoNote: "AEO lift · 14 also have thin comparison bullets",
        },
        {
          id: "q1-pdp-3",
          title: "Title missing key search term",
          skuCount: 16,
          fillTime: "~2 min",
          valueThousands: 36,
          alsoNote: "Always on · 11 overlap with missing category keywords",
        },
        {
          id: "q1-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 12,
          fillTime: "~2 min",
          valueThousands: 26,
          alsoNote: "AEO lift · 8 also missing answer-ready specs",
        },
        {
          id: "q1-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 6,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 16,
          alsoNote: "SEO copy can't publish until attributes are backfilled",
        },
      ],
      rows: [
        {
          id: "q1-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing soy-candle keyword in bullets",
          impactThousands: 34,
          findingType: "SEO",
        },
        {
          id: "q1-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready burn-time spec",
          impactThousands: 22,
          findingType: "AEO",
        },
        {
          id: "q1-pdp-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Title missing 'soy jar'",
          impactThousands: 16,
          findingType: "SEO",
        },
        {
          id: "q1-pdp-r4",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 12,
          findingType: "AEO",
        },
        {
          id: "q1-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 8,
          findingType: "SEO",
        },
      ],
    },
  ],
}
