import type { OverviewSnapshot } from "../overview-for-range"

export const q2Overview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 0.338,
    realizedMillions: 0.242,
    periodLabel: "Apr 1 – Jun 30, 2026",
    title: "Q2 content opportunity",
    pvpDelta: "+$128K vs Q1",
    pvpDeltaPositive: true,
  },
  streamsTitle: "Q2 opportunity streams",
  streamsDescription:
    "The opportunity in each stream, and how we performed against it.",
  capturedSplit: {
    retailReadinessMillions: 0.022,
    amazonOptimizationMillions: 0.075,
    seasonalMillions: 0.145,
  },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$242K",
      millions: 0.242,
      tooltip:
        "Opportunity already realized in Q2 — content changes are live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$56K",
      millions: 0.056,
      tooltip:
        "Mother's Day window closed Apr 28. $56K lost to inaction is gone for the year.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$40K",
      millions: 0.04,
      tooltip:
        "Always-on and retail-readiness dollars not captured in Q2 — rolled into Q3 rather than expiring.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Opportunity by stream",
      heading: "Q2 opportunity, by stream",
      periodBadge: "Apr 1 – Jun 30, 2026",
      heroAmountLabel: "$338K",
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$32K",
      amazonOptimizationLiftLabel: "Always-on optimization opportunity",
      amazonOptimizationLiftAmount: "$105K",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$201K",
      liftBarPct: { retailReadiness: 9, amazonOptimization: 31, seasonal: 60 },
      kpis: [],
      calcRows: [],
      calcSummary: { label: "Opportunity in Q2", value: "$338K", variant: "total" },
      methodology:
        "Seasonal loss is permanent — the window closed. Always-on and Retail readiness have no deadline, so what wasn't captured this quarter rolled into Q3's queue rather than expiring.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value realized",
      heading: "Value realized",
      periodBadge: "Apr 1 – Jun 30, 2026",
      trendBadge: { label: "+$92K vs Q1", positive: true },
      heroAmountLabel: "$242K",
      heroBordered: true,
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$22K",
      amazonOptimizationLiftLabel: "Always-on optimization opportunity",
      amazonOptimizationLiftAmount: "$75K",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$145K",
      liftBarPct: { retailReadiness: 9, amazonOptimization: 31, seasonal: 60 },
      kpis: [
        { value: "36", label: "SKUs published in Q2" },
        { value: "2.2 days", label: "Working days saved" },
        { value: "+0.3", label: "vs Q1 average" },
      ],
      calcRows: [],
      bodyCopy:
        "Captured $145K seasonal, $75K always-on, and $22K retail readiness in Q2. The $96K not captured shows as lost on the meter — seasonal is gone; always-on and retail readiness rolled into Q3.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "2.2",
      delta: "+0.3 vs Q1",
      deltaPositive: true,
      footnote: "36 actions taken · 17.4 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published, Q2", value: "36" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
          { label: "Q1 average", value: "1.9 days" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "2.2 days" },
        methodology:
          "Only published SKUs count, not ones waiting in the queue. 30 min is the full manual cycle — pull, research, draft, reload. 36 × 29 minutes = 17.4 hours, or 2.2 working days.",
      },
    },
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#4",
      delta: "▲ 1 place vs Q1",
      deltaPositive: true,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "17" },
          { label: "Median position when cited", value: "#4" },
          { label: "Q1 average", value: "#5" },
        ],
        methodology:
          "Median position where cited by Alexa AI, averaged across the quarter and compared with Q1's average on the same prompt set.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "31.2%",
      delta: "▲ 1.4 pp vs Q1",
      deltaPositive: true,
      footnote: "Weighted, up from 29.8% in Q1",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Q2 weighted share", value: "31.2%" },
          { label: "Q1 weighted share", value: "29.8%" },
          { label: "Closest competitor, Q2", value: "43%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Weighted brand citation share across tracked prompts, averaged across the quarter. Being cited first counts more than fifth.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "mothers",
        name: "Mother's Day",
        valueLabel: "$201K",
        publishBy: "Apr 28",
        skuCount: 148,
        goesLiveNote: "window closed",
      },
    ],
  },
  streams: [
    {
      id: "seasonal",
      title: "Seasonal opportunity",
      titleTooltip:
        "Optimizes content ahead of shopping events like Mother's Day, Halloween, and Black Friday.",
      context: "Mother's Day · Publish by Apr 28 ·",
      contextHighlight: "window closed",
      skuCount: 148,
      valueLabel: "$201K",
      valueKind: "potential",
      tone: "default",
      insight:
        "The window closed on Apr 28. Captured **$145K**; **$56K** lost to inaction is gone for the year — it does not come back.",
      remainingLabel: "142 more SKUs worth $129K, ranked by impact.",
      buckets: [
        {
          id: "q2-sea-1",
          title: "No occasion keyword in title",
          skuCount: 52,
          fillTime: "~3 min",
          valueThousands: 85,
          alsoNote: "Publish by Apr 28 · 31 also need gift notes in bullets",
          outcome: "captured",
        },
        {
          id: "q2-sea-2",
          title: "Bullets don't mention gifting",
          skuCount: 38,
          fillTime: "~2 min",
          valueThousands: 60,
          alsoNote: "Mother's Day window · 24 also missing a floral note",
          outcome: "captured",
        },
        {
          id: "q2-sea-3",
          title: "Gift-set contents not listed",
          skuCount: 28,
          fillTime: "~2 min",
          valueThousands: 28,
          alsoNote: "Gift sets · 16 also missing an occasion keyword",
          outcome: "missed",
        },
        {
          id: "q2-sea-4",
          title: "Blocked — attributes missing first",
          skuCount: 18,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 16,
          alsoNote: "Seasonal copy can't publish until attributes are backfilled",
          outcome: "missed",
        },
        {
          id: "q2-sea-5",
          title: "No spring scent framing",
          skuCount: 12,
          fillTime: "~2 min",
          valueThousands: 12,
          alsoNote: "Floral jars · 8 also have thin bullets",
          outcome: "missed",
        },
      ],
      rows: [
        {
          id: "q2-sea-r1",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "No Mother's Day keyword in title",
          impactThousands: 28,
        },
        {
          id: "q2-sea-r2",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Bullets don't mention gifting",
          impactThousands: 22,
        },
        {
          id: "q2-sea-r3",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Gift-set contents not listed",
          impactThousands: 16,
        },
        {
          id: "q2-sea-r4",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "No spring scent framing",
          impactThousands: 12,
        },
        {
          id: "q2-sea-r5",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Title truncated before the occasion",
          impactThousands: 9,
        },
        {
          id: "q2-sea-r6",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "Bullets 3 and 4 empty",
          impactThousands: 6,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always-on optimization opportunity",
      titleTooltip:
        "Keeps listings aligned with brand and retailer guidelines as category trends shift.",
      context: "Always on · SEO and AEO · No deadline",
      skuCount: 126,
      valueLabel: "$105K",
      valueKind: "potential",
      tone: "default",
      insight:
        "No deadline on this stream. Captured **$75K** in Q2; the **$30K** not yet captured rolled into Q3's queue — it is not lost.",
      remainingLabel: "121 more SKUs worth $60K, ranked by impact.",
      buckets: [
        {
          id: "q2-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 44,
          fillTime: "~2 min",
          valueThousands: 42,
          alsoNote: "SEO lift · 28 also missing a search term in the title",
          outcome: "captured",
        },
        {
          id: "q2-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 32,
          fillTime: "~3 min",
          valueThousands: 33,
          alsoNote: "AEO lift · 19 also have thin comparison bullets",
          outcome: "captured",
        },
        {
          id: "q2-pdp-3",
          title: "Title missing key search term",
          skuCount: 24,
          fillTime: "~2 min",
          valueThousands: 15,
          alsoNote: "Always on · 16 overlap with missing category keywords",
        },
        {
          id: "q2-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 16,
          fillTime: "~2 min",
          valueThousands: 10,
          alsoNote: "AEO lift · 11 also missing answer-ready specs",
        },
        {
          id: "q2-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 10,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 5,
          alsoNote: "SEO copy can't publish until attributes are backfilled",
        },
      ],
      rows: [
        {
          id: "q2-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing spring category keywords in bullets",
          impactThousands: 18,
          findingType: "SEO",
        },
        {
          id: "q2-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready wax-type spec",
          impactThousands: 14,
          findingType: "AEO",
        },
        {
          id: "q2-pdp-r3",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Title missing '3-wick'",
          impactThousands: 10,
          findingType: "SEO",
        },
        {
          id: "q2-pdp-r4",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 8,
          findingType: "AEO",
        },
        {
          id: "q2-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 5,
          findingType: "SEO",
        },
      ],
    },
    {
      id: "retail-readiness",
      title: "Retail readiness opportunity",
      titleTooltip:
        "Cleans up backend catalog data so SKUs meet retailer syndication requirements.",
      context: "Vendor Central attribute gaps · No deadline",
      skuCount: 78,
      valueLabel: "$32K",
      valueKind: "blocked",
      tone: "default",
      insight:
        "No deadline on this stream. Captured **$22K** in Q2; the **$10K** not yet captured rolled into Q3's queue — it is not lost.",
      remainingLabel: "74 more SKUs, $20K blocked in total.",
      buckets: [
        {
          id: "q2-rr-mandatory",
          title: "Agent-drafted, ready for approval",
          skuCount: 34,
          fillTime: "~1 min each",
          valueThousands: 22,
          badge: "Approval required",
          alsoNote:
            "These SKUs are not syndicatable. Make your catalog retail ready and unblock syndication.",
          outcome: "captured",
        },
        {
          id: "q2-rr-recommended",
          title: "Missing mandatory attributes",
          skuCount: 44,
          fillMode: "input",
          fillTime: "~1-2 min each",
          valueThousands: 10,
          badge: "Input required",
          alsoNote:
            "This will improve search and answer engine citation rate.",
        },
      ],
      rows: [
        {
          id: "q2-rr-r1",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Unit price missing on the Q2 feed",
          impactThousands: 5,
        },
        {
          id: "q2-rr-r2",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Item weight missing",
          impactThousands: 3,
        },
        {
          id: "q2-rr-r3",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "Safety sheet not attached",
          impactThousands: 2,
        },
        {
          id: "q2-rr-r4",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Material composition blank",
          impactThousands: 1,
        },
      ],
    },
  ],
}
