import type { OverviewSnapshot } from "../overview-for-range"

export const q2Overview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 0.88,
    realizedMillions: 0.15,
    periodLabel: "Apr 1 – Jun 30, 2026",
  },
  capturedSplit: { foundationalMillions: 0.1, seasonalMillions: 0.05 },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$150K",
      millions: 0.15,
      tooltip:
        "Opportunity already realized in Q2 — content changes are live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$660K",
      millions: 0.66,
      tooltip:
        "Mother's Day window. Publish by Apr 28 to capture the lift before the moment passes.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$70K",
      millions: 0.07,
      tooltip:
        "Always-on SEO and AEO lifts identified in Q2, with no hard event deadline.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Annualized opportunity",
      heading: "Q2 opportunity",
      periodBadge: "Apr 1 – Jun 30, 2026",
      heroAmountLabel: "$0.88M",
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$0.22M",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$0.66M",
      liftBarPct: { foundational: 25, seasonal: 75 },
      kpis: [
        { value: "12", label: "SKUs A/B tested in Q2" },
        { value: "+3.1%", label: "Median sales lift" },
        { value: "9 of 12", label: "Challenger won" },
      ],
      calcRows: [
        { label: "Revenue, SKUs not yet optimized in Q2", value: "$7.33M" },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Foundational lift", value: "$0.22M", variant: "subtotal" },
        {
          label: "Revenue in the 2 weeks around Mother's Day",
          value: "$22.00M",
        },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Seasonal lift", value: "$0.66M", variant: "subtotal" },
      ],
      calcSummary: { label: "Opportunity in Q2", value: "$0.88M", variant: "total" },
      methodology:
        "Q2 revenue comes from Vendor Central history for Apr 1 – Jun 30. $7.33M × 3.0% = $0.22M. $22.00M × 3.0% = $0.66M. Together that is $0.88M.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value Realized",
      heading: "Value realized",
      periodBadge: "Apr 1 – Jun 30, 2026",
      trendBadge: { label: "+$60K vs prior month", positive: true },
      heroAmountLabel: "$150K",
      heroBordered: true,
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$100K",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$50K",
      liftBarPct: { foundational: 67, seasonal: 33 },
      kpis: [
        { value: "36", label: "SKUs live" },
        { value: "3.0 days", label: "Median approve-to-live" },
        { value: "Q2", label: "Accruing this quarter" },
      ],
      calcRows: [],
      bodyCopy:
        "Counts only the 36 SKUs published in Q2, accrued over the days their content was actually live in the Apr 1 – Jun 30 window.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "2.2",
      delta: "7% productivity boost WoW",
      deltaPositive: true,
      footnote: "36 actions taken · 17.4 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published in Q2", value: "36" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
          { label: "Total saved", value: "17.4 hrs" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "2.2 days" },
        methodology:
          "Time saved counts only SKUs published in this quarter. 36 SKUs × 29 minutes = 17.4 hours, or 2.2 working days.",
      },
    },
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#4",
      delta: "▲ 1 place vs prior week",
      deltaPositive: true,
      live: true,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "16" },
          { label: "Median position when cited", value: "#4" },
        ],
        summaryRow: { label: "Prior week in Q2", value: "#5" },
        methodology:
          "Standing at the end of Q2, not the full-year median. Prompts where you don't appear are excluded from the median.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "31.2%",
      delta: "▲ 1.4 pp WoW",
      deltaPositive: true,
      live: true,
      footnote: "Weighted, up from 29.8% the week before",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Your weighted share in Q2", value: "31.2%" },
          { label: "Prior week", value: "29.8%" },
          { label: "Closest competitor", value: "42%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Share of brand citations in the Q2 prompt runs, weighted by position. 31.2% − 29.8% = 1.4 percentage points.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "mothers",
        name: "Mother's Day",
        valueLabel: "$660K",
        publishBy: "Apr 28",
        skuCount: 148,
        goesLiveNote: "window closed",
      },
    ],
  },
  retrospective: {
    heading: "Q2 recap",
    highlights: [
      {
        id: "q2-h1",
        title: "Mother's Day copy shipped on the top 36 SKUs",
        amountLabel: "$50K",
      },
      {
        id: "q2-h2",
        title: "Unit price and item weight backfilled on 48 SKUs",
        amountLabel: "$100K",
      },
    ],
    lowlights: [
      {
        id: "q2-l1",
        title: "112 Mother's Day SKUs never published",
        amountLabel: "$610K",
      },
    ],
  },
  streams: [
    {
      id: "retail-readiness",
      title: "Retail-readiness",
      context: "of catalog is retail-ready",
      skuCount: 78,
      valueLabel: "$104K",
      valueKind: "blocked",
      tone: "warning",
      readyPercent: 96,
      insight:
        "**78 SKUs** are missing required **Amazon attributes** in the Q2 catalog pull. Amazon won’t accept a content push until these are backfilled, so **$104K** of **PDP fixes** queued this quarter are stuck behind this.",
      remainingLabel: "74 more SKUs, $78K blocked in total.",
      buckets: [
        {
          id: "q2-rr-1",
          title: "Unit price missing",
          skuCount: 28,
          fillTime: "~1 min",
          valueThousands: 36,
          releasesThousands: 8,
          alsoNote: "22 also have thin Mother's Day bullets",
          outcome: "captured",
        },
        {
          id: "q2-rr-2",
          title: "Item weight missing",
          skuCount: 20,
          fillTime: "~1 min",
          valueThousands: 28,
          releasesThousands: 5,
          alsoNote: "15 also missing burn-time specs",
          outcome: "captured",
        },
        {
          id: "q2-rr-3",
          title: "Safety & compliance docs missing",
          skuCount: 14,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 18,
          releasesThousands: 3,
          alsoNote: "10 also have title gaps",
          outcome: "missed",
        },
        {
          id: "q2-rr-4",
          title: "Material composition missing",
          skuCount: 10,
          fillTime: "~1 min",
          valueThousands: 14,
          releasesThousands: 2,
          alsoNote: "8 also have thin bullets",
          outcome: "missed",
        },
        {
          id: "q2-rr-5",
          title: "Country of origin missing",
          skuCount: 6,
          fillTime: "~1 min",
          valueThousands: 8,
          releasesThousands: 1,
          alsoNote: "5 also have title gaps",
          outcome: "missed",
        },
      ],
      rows: [
        {
          id: "q2-rr-r1",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Unit price missing on the Q2 feed",
          impactThousands: 11,
        },
        {
          id: "q2-rr-r2",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Item weight missing",
          impactThousands: 7,
        },
        {
          id: "q2-rr-r3",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "Safety sheet not attached",
          impactThousands: 5,
        },
        {
          id: "q2-rr-r4",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Material composition blank",
          impactThousands: 3,
        },
      ],
    },
    {
      id: "seasonal",
      title: "Seasonal",
      context: "Mother's Day · Publish by Apr 28 ·",
      contextHighlight: "window closed",
      skuCount: 148,
      valueLabel: "$660K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**148 SKUs** are missing gifting language, occasion keywords, or bundle notes for **Mother's Day**. Ranked by revenue, the **top 20** carry about **a third of the $660K**.",
      remainingLabel: "142 more SKUs worth $418K, ranked by impact.",
      buckets: [
        {
          id: "q2-sea-1",
          title: "No occasion keyword in title",
          skuCount: 52,
          fillTime: "~3 min",
          valueThousands: 220,
          alsoNote: "Publish by Apr 28 · 31 also need gift notes in bullets",
          outcome: "captured",
        },
        {
          id: "q2-sea-2",
          title: "Bullets don't mention gifting",
          skuCount: 38,
          fillTime: "~2 min",
          valueThousands: 170,
          alsoNote: "Mother's Day window · 24 also missing a floral note",
          outcome: "missed",
        },
        {
          id: "q2-sea-3",
          title: "Gift-set contents not listed",
          skuCount: 28,
          fillTime: "~2 min",
          valueThousands: 130,
          alsoNote: "Gift sets · 16 also missing an occasion keyword",
          outcome: "missed",
        },
        {
          id: "q2-sea-4",
          title: "Blocked — attributes missing first",
          skuCount: 18,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 80,
          alsoNote: "Seasonal copy can't publish until attributes are backfilled",
          outcome: "missed",
        },
        {
          id: "q2-sea-5",
          title: "No spring scent framing",
          skuCount: 12,
          fillTime: "~2 min",
          valueThousands: 60,
          alsoNote: "Floral jars · 8 also have thin bullets",
          outcome: "missed",
        },
      ],
      rows: [
        {
          id: "q2-sea-r1",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "No Mother's Day keyword in title",
          impactThousands: 72,
        },
        {
          id: "q2-sea-r2",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Bullets don't mention gifting",
          impactThousands: 54,
        },
        {
          id: "q2-sea-r3",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Gift-set contents not listed",
          impactThousands: 41,
        },
        {
          id: "q2-sea-r4",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "No spring scent framing",
          impactThousands: 33,
        },
        {
          id: "q2-sea-r5",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Title truncated before the occasion",
          impactThousands: 24,
        },
        {
          id: "q2-sea-r6",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "Bullets 3 and 4 empty",
          impactThousands: 18,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always on optimization",
      context: "Q2 · SEO & AEO · No deadline",
      skuCount: 126,
      valueLabel: "$340K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**126 SKUs** identified in Q2 are missing category keywords or the structured specs an **AI answer engine** needs to cite the listing.",
      remainingLabel: "121 more SKUs worth $190K, ranked by impact.",
      buckets: [
        {
          id: "q2-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 44,
          fillTime: "~2 min",
          valueThousands: 120,
          alsoNote: "SEO lift · 28 also missing a search term in the title",
        },
        {
          id: "q2-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 32,
          fillTime: "~3 min",
          valueThousands: 90,
          alsoNote: "AEO lift · 19 also have thin comparison bullets",
        },
        {
          id: "q2-pdp-3",
          title: "Title missing key search term",
          skuCount: 24,
          fillTime: "~2 min",
          valueThousands: 60,
          alsoNote: "Always on · 16 overlap with missing category keywords",
        },
        {
          id: "q2-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 16,
          fillTime: "~2 min",
          valueThousands: 42,
          alsoNote: "AEO lift · 11 also missing answer-ready specs",
        },
        {
          id: "q2-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 10,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 28,
          alsoNote: "SEO copy can't publish until attributes are backfilled",
        },
      ],
      rows: [
        {
          id: "q2-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing spring category keywords in bullets",
          impactThousands: 48,
          findingType: "SEO",
        },
        {
          id: "q2-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready wax-type spec",
          impactThousands: 36,
          findingType: "AEO",
        },
        {
          id: "q2-pdp-r3",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Title missing '3-wick'",
          impactThousands: 28,
          findingType: "SEO",
        },
        {
          id: "q2-pdp-r4",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 22,
          findingType: "AEO",
        },
        {
          id: "q2-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 16,
          findingType: "SEO",
        },
      ],
    },
  ],
}
