import type { OverviewSnapshot } from "../overview-for-range"

export const q3Overview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 1.65,
    realizedMillions: 0.3,
    periodLabel: "Jul 1 – Sep 30, 2026",
  },
  capturedSplit: { foundationalMillions: 0.2, seasonalMillions: 0.1 },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$300K",
      millions: 0.3,
      tooltip:
        "Opportunity already realized in Q3 — content changes are live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$1.24M",
      millions: 1.24,
      tooltip:
        "Black Friday window. Publish by Sep 15 to capture the lift before the moment passes.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$110K",
      millions: 0.11,
      tooltip:
        "Always-on SEO and AEO lifts identified in Q3, with no hard event deadline.",
    },
    {
      id: "expired",
      label: "Expired",
      amountLabel: "$890K",
      millions: 0.89,
      muted: true,
      tooltip:
        "Prime Day, Jul 2026. 210 deal SKUs still had gaps when the window closed — excluded from the Q3 active total.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Annualized opportunity",
      heading: "Q3 opportunity",
      periodBadge: "Jul 1 – Sep 30, 2026",
      heroAmountLabel: "$1.65M",
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$0.41M",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$1.24M",
      liftBarPct: { foundational: 25, seasonal: 75 },
      kpis: [
        { value: "18", label: "SKUs A/B tested in Q3" },
        { value: "+3.0%", label: "Median sales lift" },
        { value: "14 of 18", label: "Challenger won" },
      ],
      calcRows: [
        { label: "Revenue, SKUs not yet optimized in Q3", value: "$13.67M" },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Foundational lift", value: "$0.41M", variant: "subtotal" },
        {
          label: "Revenue in the 2 weeks around Black Friday publish",
          value: "$41.33M",
        },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Seasonal lift", value: "$1.24M", variant: "subtotal" },
      ],
      calcSummary: { label: "Opportunity in Q3", value: "$1.65M", variant: "total" },
      methodology:
        "Q3 revenue comes from Vendor Central history for Jul 1 – Sep 30. $13.67M × 3.0% = $0.41M. $41.33M × 3.0% = $1.24M. Together that is $1.65M. Prime Day's missed $890K is excluded.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value Realized",
      heading: "Value realized",
      periodBadge: "Jul 1 – Sep 30, 2026",
      trendBadge: { label: "+$120K this month", positive: true },
      heroAmountLabel: "$300K",
      heroBordered: true,
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$200K",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$100K",
      liftBarPct: { foundational: 67, seasonal: 33 },
      kpis: [
        { value: "48", label: "SKUs live" },
        { value: "2.8 days", label: "Median approve-to-live" },
        { value: "Q3", label: "Accruing this quarter" },
      ],
      calcRows: [],
      bodyCopy:
        "Counts only the 48 SKUs published in Q3, accrued over the days their content was actually live in the Jul 1 – Sep 30 window.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      unrealized: {
        title: "Identified but never published",
        amountLabel: "$890K",
        description:
          "Prime Day, Jul 2026. 210 deal SKUs still had gaps when syndication cut off. Not part of the $1.65M above and not recoverable.",
      },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "2.9",
      delta: "8% productivity boost WoW",
      deltaPositive: true,
      footnote: "48 actions taken · 23.2 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published in Q3", value: "48" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
          { label: "Total saved", value: "23.2 hrs" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "2.9 days" },
        methodology:
          "Time saved counts only SKUs published in this quarter. 48 SKUs × 29 minutes = 23.2 hours, or 2.9 working days.",
      },
    },
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#3",
      delta: "▲ 1 place vs prior week",
      deltaPositive: true,
      live: true,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "17" },
          { label: "Median position when cited", value: "#3" },
        ],
        summaryRow: { label: "Prior week in Q3", value: "#4" },
        methodology:
          "Standing at the end of Q3, not the full-year median. Prompts where you don't appear are excluded from the median.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "32.6%",
      delta: "▲ 1.5 pp WoW",
      deltaPositive: true,
      live: true,
      footnote: "Weighted, up from 31.1% the week before",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Your weighted share in Q3", value: "32.6%" },
          { label: "Prior week", value: "31.1%" },
          { label: "Closest competitor", value: "40%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Share of brand citations in the Q3 prompt runs, weighted by position. 32.6% − 31.1% = 1.5 percentage points.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "bf",
        name: "Black Friday",
        valueLabel: "$1.24M",
        publishBy: "Sep 15",
        skuCount: 384,
        goesLiveNote: "4 days later",
      },
    ],
  },
  streams: [
    {
      id: "retail-readiness",
      title: "Retail-readiness",
      context: "of catalog is retail-ready",
      skuCount: 112,
      valueLabel: "$148K",
      valueKind: "blocked",
      tone: "warning",
      readyPercent: 95,
      insight:
        "**112 SKUs** are missing required **Amazon attributes** in the Q3 catalog pull. Amazon won’t accept a content push until these are backfilled, so **$148K** of **PDP fixes** queued this quarter are stuck behind this.",
      remainingLabel: "108 more SKUs, $115K blocked in total.",
      buckets: [
        {
          id: "q3-rr-1",
          title: "Unit price missing",
          skuCount: 40,
          fillTime: "~1 min",
          valueThousands: 48,
          releasesThousands: 11,
          alsoNote: "32 also have thin Black Friday bullets",
        },
        {
          id: "q3-rr-2",
          title: "Item weight missing",
          skuCount: 28,
          fillTime: "~1 min",
          valueThousands: 36,
          releasesThousands: 7,
          alsoNote: "21 also missing burn-time specs",
        },
        {
          id: "q3-rr-3",
          title: "Safety & compliance docs missing",
          skuCount: 20,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 28,
          releasesThousands: 5,
          alsoNote: "14 also have title gaps",
        },
        {
          id: "q3-rr-4",
          title: "Material composition missing",
          skuCount: 14,
          fillTime: "~1 min",
          valueThousands: 22,
          releasesThousands: 3,
          alsoNote: "10 also have thin bullets",
        },
        {
          id: "q3-rr-5",
          title: "Country of origin missing",
          skuCount: 10,
          fillTime: "~1 min",
          valueThousands: 14,
          releasesThousands: 2,
          alsoNote: "7 also have title gaps",
        },
      ],
      rows: [
        {
          id: "q3-rr-r1",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "6 attributes missing — material, weight, safety",
          impactThousands: 14,
        },
        {
          id: "q3-rr-r2",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Item weight missing on the Q3 feed",
          impactThousands: 9,
        },
        {
          id: "q3-rr-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Safety sheet not attached",
          impactThousands: 6,
        },
        {
          id: "q3-rr-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Country of origin blank",
          impactThousands: 4,
        },
      ],
    },
    {
      id: "seasonal",
      title: "Seasonal",
      context: "Next up · Black Friday · Publish by Sep 15 ·",
      contextHighlight: "5 days to act",
      skuCount: 384,
      valueLabel: "$1.24M",
      valueKind: "potential",
      tone: "default",
      insight:
        "**384 SKUs** are missing event-ready titles, deal framing, or bundle language for **Black Friday**. I ranked them by revenue each fix is worth, so the **top 20** carry about **a third of the $1.24M**.",
      queueNote:
        "Cyber Monday ($860K) and Holiday Gift Guide ($510K) are queued next — they’ll open here once this window closes.",
      remainingLabel: "378 more SKUs worth $882K, ranked by impact.",
      buckets: [
        {
          id: "q3-sea-1",
          title: "No promo keyword in title",
          skuCount: 142,
          fillTime: "~3 min",
          valueThousands: 420,
          alsoNote: "Publish by Sep 15 · 98 of these also need deal terms in bullets",
        },
        {
          id: "q3-sea-2",
          title: "Bullets don't state the deal terms",
          skuCount: 118,
          fillTime: "~2 min",
          valueThousands: 380,
          alsoNote: "Black Friday window · 76 also missing holiday urgency language",
        },
        {
          id: "q3-sea-3",
          title: "No holiday urgency language",
          skuCount: 96,
          fillTime: "~2 min",
          valueThousands: 210,
          alsoNote: "5 days to act · 48 also missing a promo keyword in the title",
        },
        {
          id: "q3-sea-4",
          title: "Blocked — attributes missing first",
          skuCount: 74,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 140,
          alsoNote: "Seasonal copy can't publish until Amazon attributes are backfilled",
        },
        {
          id: "q3-sea-5",
          title: "Gift-set bundle not described",
          skuCount: 52,
          fillTime: "~2 min",
          valueThousands: 90,
          alsoNote: "Gift sets · 31 also missing a promo keyword in the title",
        },
      ],
      rows: [
        {
          id: "q3-sea-r1",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "No promo keyword in title",
          impactThousands: 84,
        },
        {
          id: "q3-sea-r2",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "Bullets don't state the deal terms",
          impactThousands: 71,
        },
        {
          id: "q3-sea-r3",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Bundle contents not described",
          impactThousands: 63,
        },
        {
          id: "q3-sea-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "No Black Friday urgency language",
          impactThousands: 52,
        },
        {
          id: "q3-sea-r5",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Title truncated at 142 characters",
          impactThousands: 47,
        },
        {
          id: "q3-sea-r6",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Bullets 4 and 5 empty",
          impactThousands: 41,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always on optimization",
      context: "Q3 · SEO & AEO · No deadline",
      skuCount: 186,
      valueLabel: "$480K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**186 SKUs** identified in Q3 are missing category keywords or the structured specs an **AI answer engine** needs to cite the listing.",
      remainingLabel: "181 more SKUs worth $292K, ranked by impact.",
      buckets: [
        {
          id: "q3-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 68,
          fillTime: "~2 min",
          valueThousands: 170,
          alsoNote: "SEO lift · 41 also missing a search term in the title",
        },
        {
          id: "q3-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 48,
          fillTime: "~3 min",
          valueThousands: 130,
          alsoNote: "AEO lift · 29 also have thin comparison bullets",
        },
        {
          id: "q3-pdp-3",
          title: "Title missing key search term",
          skuCount: 32,
          fillTime: "~2 min",
          valueThousands: 80,
          alsoNote: "Always on · 22 overlap with missing category keywords",
        },
        {
          id: "q3-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 24,
          fillTime: "~2 min",
          valueThousands: 60,
          alsoNote: "AEO lift · 15 also missing answer-ready specs",
        },
        {
          id: "q3-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 14,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 40,
          alsoNote: "SEO copy can't publish until attributes are backfilled",
        },
      ],
      rows: [
        {
          id: "q3-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing top category keywords in bullets",
          impactThousands: 62,
          findingType: "SEO",
        },
        {
          id: "q3-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready specs for 'best candle' prompts",
          impactThousands: 44,
          findingType: "AEO",
        },
        {
          id: "q3-pdp-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Title missing key search term 'soy jar'",
          impactThousands: 36,
          findingType: "SEO",
        },
        {
          id: "q3-pdp-r4",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 28,
          findingType: "AEO",
        },
        {
          id: "q3-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 18,
          findingType: "SEO",
        },
      ],
    },
  ],
}
