import type { OverviewSnapshot } from "../overview-for-range"

export const q3Overview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 0.75,
    realizedMillions: 0.3,
    periodLabel: "Jul 1 – Sep 30, 2026",
    pvpDelta: "+$770K PvP",
    pvpDeltaPositive: true,
  },
  capturedSplit: {
    retailReadinessMillions: 0.04,
    amazonOptimizationMillions: 0.16,
    seasonalMillions: 0.1,
  },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$300K",
      millions: 0.3,
      tooltip:
        "Opportunity already realized in Q3 — content changes are live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$335K",
      millions: 0.335,
      tooltip:
        "Halloween window. Publish by Oct 8 to capture the lift before the moment passes.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$110K",
      millions: 0.11,
      tooltip:
        "Always-on SEO and AEO lifts identified in Q3, with no hard event deadline.",
    },
    {
      id: "expired",
      label: "Expired",
      amountLabel: "$890K",
      millions: 0.89,
      muted: true,
      tooltip:
        "Prime Day, Jul 2026. 210 deal SKUs still had gaps when the window closed — excluded from the Q3 active total.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Annualized opportunity",
      heading: "Q3 opportunity",
      periodBadge: "Jul 1 – Sep 30, 2026",
      heroAmountLabel: "$0.75M",
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$0.07M",
      amazonOptimizationLiftLabel: "Amazon optimization opportunity",
      amazonOptimizationLiftAmount: "$0.34M",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$0.34M",
      liftBarPct: { retailReadiness: 9, amazonOptimization: 45, seasonal: 46 },
      kpis: [
        { value: "18", label: "SKUs A/B tested in Q3" },
        { value: "+3.0%", label: "Median sales lift" },
        { value: "14 of 18", label: "Challenger won" },
      ],
      calcRows: [
        {
          label: "Revenue on attribute-blocked SKUs in Q3",
          value: "$2.33M",
        },
        { label: "× banked lift rate", value: "3.0%" },
        {
          label: "Retail readiness opportunity",
          value: "$0.07M",
          variant: "subtotal",
        },
        {
          label: "Revenue on always-on SEO & AEO gaps in Q3",
          value: "$11.34M",
        },
        { label: "× banked lift rate", value: "3.0%" },
        {
          label: "Amazon optimization opportunity",
          value: "$0.34M",
          variant: "subtotal",
        },
        {
          label: "Revenue in the 2 weeks around Halloween publish",
          value: "$11.17M",
        },
        { label: "× banked lift rate", value: "3.0%" },
        {
          label: "Seasonal opportunity",
          value: "$0.34M",
          variant: "subtotal",
        },
      ],
      calcSummary: { label: "Opportunity in Q3", value: "$0.75M", variant: "total" },
      methodology:
        "Q3 revenue comes from Vendor Central history for Jul 1 – Sep 30. $2.33M × 3.0% = $0.07M. $11.34M × 3.0% = $0.34M. $11.17M × 3.0% = $0.34M. Together that is $0.75M. Prime Day's missed $890K is excluded.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value Realized",
      heading: "Value realized",
      periodBadge: "Jul 1 – Sep 30, 2026",
      trendBadge: { label: "+$120K this month", positive: true },
      heroAmountLabel: "$300K",
      heroBordered: true,
      retailReadinessLiftLabel: "Retail readiness opportunity",
      retailReadinessLiftAmount: "$40K",
      amazonOptimizationLiftLabel: "Amazon optimization opportunity",
      amazonOptimizationLiftAmount: "$160K",
      seasonalLiftLabel: "Seasonal opportunity",
      seasonalLiftAmount: "$100K",
      liftBarPct: { retailReadiness: 13, amazonOptimization: 54, seasonal: 33 },
      kpis: [
        { value: "48", label: "SKUs live" },
        { value: "2.8 days", label: "Median approve-to-live" },
        { value: "Q3", label: "Accruing this quarter" },
      ],
      calcRows: [],
      bodyCopy:
        "Counts only the 48 SKUs published in Q3, accrued over the days their content was actually live in the Jul 1 – Sep 30 window.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      unrealized: {
        title: "Identified but never published",
        amountLabel: "$890K",
        description:
          "Prime Day, Jul 2026. 210 deal SKUs still had gaps when syndication cut off. Not part of the $1.65M above and not recoverable.",
      },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "2.9",
      delta: "8% productivity boost WoW",
      deltaPositive: true,
      footnote: "48 actions taken · 23.2 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published in Q3", value: "48" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
          { label: "Total saved", value: "23.2 hrs" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "2.9 days" },
        methodology:
          "Time saved counts only SKUs published in this quarter. 48 SKUs × 29 minutes = 23.2 hours, or 2.9 working days.",
      },
    },
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#3",
      delta: "▲ 1 place vs prior week",
      deltaPositive: true,
      live: true,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "17" },
          { label: "Median position when cited", value: "#3" },
        ],
        summaryRow: { label: "Prior week in Q3", value: "#4" },
        methodology:
          "Standing at the end of Q3, not the full-year median. Prompts where you don't appear are excluded from the median.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "32.6%",
      delta: "▲ 1.5 pp WoW",
      deltaPositive: true,
      live: true,
      footnote: "Weighted, up from 31.1% the week before",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Your weighted share in Q3", value: "32.6%" },
          { label: "Prior week", value: "31.1%" },
          { label: "Closest competitor", value: "40%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Share of brand citations in the Q3 prompt runs, weighted by position. 32.6% − 31.1% = 1.5 percentage points.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "hw",
        name: "Halloween",
        valueLabel: "$335K",
        publishBy: "Oct 8",
        skuCount: 128,
        goesLiveNote: "Oct 31",
      },
    ],
  },
  streams: [
    {
      id: "seasonal",
      title: "Seasonal opportunity",
      context: "Next up · Halloween · Publish by Oct 8 ·",
      contextHighlight: "20 days to act",
      skuCount: 128,
      valueLabel: "$335K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**100 SKUs** are missing **Amazon-required attributes**. Fixing these gaps will make the full catalog ready for syndication and more frequent updates.",
      queueNote:
        "Cyber Monday ($860K) and Holiday Gift Guide ($510K) are queued next — they’ll open here once this window closes.",
      remainingLabel: "122 more SKUs worth $251K, ranked by impact.",
      buckets: [
        {
          id: "q3-sea-hw",
          title: "Halloween",
          skuCount: 128,
          fillTime: "~35 min total",
          badge: "Improves SEO & AEO",
          momentId: "hw",
        },
      ],
      rows: [
        {
          id: "q3-sea-r1",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "No Halloween keyword in title",
          impactThousands: 84,
        },
        {
          id: "q3-sea-r2",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "Bullets don't mention seasonal scent",
          impactThousands: 71,
        },
        {
          id: "q3-sea-r3",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Bundle contents not described",
          impactThousands: 63,
        },
        {
          id: "q3-sea-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "No Halloween urgency language",
          impactThousands: 52,
        },
        {
          id: "q3-sea-r5",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Title truncated at 142 characters",
          impactThousands: 47,
        },
        {
          id: "q3-sea-r6",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Bullets 4 and 5 empty",
          impactThousands: 41,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always-on optimization opportunity",
      context: "Q3 · SEO & AEO · No deadline",
      skuCount: 186,
      valueLabel: "$480K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**186 SKUs** identified in Q3 are missing category keywords or the structured specs an **AI answer engine** needs to cite the listing.",
      remainingLabel: "181 more SKUs worth $292K, ranked by impact.",
      buckets: [
        {
          id: "q3-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 68,
          fillTime: "~2 min",
          valueThousands: 170,
          alsoNote: "SEO lift · 41 also missing a search term in the title",
        },
        {
          id: "q3-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 48,
          fillTime: "~3 min",
          valueThousands: 130,
          alsoNote: "AEO lift · 29 also have thin comparison bullets",
        },
        {
          id: "q3-pdp-3",
          title: "Title missing key search term",
          skuCount: 32,
          fillTime: "~2 min",
          valueThousands: 80,
          alsoNote: "Always on · 22 overlap with missing category keywords",
        },
        {
          id: "q3-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 24,
          fillTime: "~2 min",
          valueThousands: 60,
          alsoNote: "AEO lift · 15 also missing answer-ready specs",
        },
        {
          id: "q3-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 14,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 40,
          alsoNote: "SEO copy can't publish until attributes are backfilled",
        },
      ],
      rows: [
        {
          id: "q3-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing top category keywords in bullets",
          impactThousands: 62,
          findingType: "SEO",
        },
        {
          id: "q3-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready specs for 'best candle' prompts",
          impactThousands: 44,
          findingType: "AEO",
        },
        {
          id: "q3-pdp-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Title missing key search term 'soy jar'",
          impactThousands: 36,
          findingType: "SEO",
        },
        {
          id: "q3-pdp-r4",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 28,
          findingType: "AEO",
        },
        {
          id: "q3-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 18,
          findingType: "SEO",
        },
      ],
    },
    {
      id: "retail-readiness",
      title: "Retail readiness opportunity",
      context: "Vendor Central Attribute Gaps",
      skuCount: 112,
      valueLabel: "$148K",
      valueKind: "blocked",
      tone: "default",
      insight:
        "**112 SKUs** are missing required **Amazon attributes** in the Q3 catalog pull. Amazon won’t accept a content push until these are backfilled, so **$148K** of **PDP fixes** queued this quarter are stuck behind this.",
      remainingLabel: "108 more SKUs, $115K blocked in total.",
      buckets: [
        {
          id: "q3-rr-mandatory",
          title: "Agent-drafted, ready for approval",
          skuCount: 35,
          fillTime: "~1 min each",
          badge: "Approval required",
          alsoNote:
            "These SKUs are not syndicatable. Make your catalog retail ready and unblock syndication.",
        },
        {
          id: "q3-rr-recommended",
          title: "Missing mandatory attributes",
          skuCount: 77,
          fillMode: "input",
          fillTime: "~1-2 min each",
          badge: "Input required",
          alsoNote:
            "This will improve search and answer engine citation rate.",
        },
      ],
      rows: [
        {
          id: "q3-rr-r1",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "6 attributes missing — material, weight, safety",
          impactThousands: 14,
        },
        {
          id: "q3-rr-r2",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Item weight missing on the Q3 feed",
          impactThousands: 9,
        },
        {
          id: "q3-rr-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Safety sheet not attached",
          impactThousands: 6,
        },
        {
          id: "q3-rr-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "Country of origin blank",
          impactThousands: 4,
        },
      ],
    },
  ],
}
