import type { OverviewSnapshot } from "../overview-for-range"

export const q4Overview: OverviewSnapshot = {
  meter: {
    identifiedMillions: 1.75,
    realizedMillions: 0.25,
    periodLabel: "Oct 1 – Dec 31, 2026",
  },
  capturedSplit: { foundationalMillions: 0.16, seasonalMillions: 0.09 },
  status: [
    {
      id: "captured",
      label: "Captured",
      amountLabel: "$250K",
      millions: 0.25,
      tooltip:
        "Opportunity already realized in Q4 — content changes are live on retailer PDPs.",
    },
    {
      id: "seasonal",
      label: "Seasonal",
      amountLabel: "$1.37M",
      millions: 1.37,
      tooltip:
        "Cyber Monday ($860K) plus Holiday Gift Guide ($510K). Publish Cyber Monday by Nov 20.",
    },
    {
      id: "pdp",
      label: "PDP optimization",
      amountLabel: "$130K",
      millions: 0.13,
      tooltip:
        "Always-on SEO and AEO lifts identified in Q4, with no hard event deadline.",
    },
  ],
  calculation: {
    annualized: {
      id: "annualized",
      tabLabel: "Annualized opportunity",
      heading: "Q4 opportunity",
      periodBadge: "Oct 1 – Dec 31, 2026",
      heroAmountLabel: "$1.75M",
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$0.38M",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$1.37M",
      liftBarPct: { foundational: 22, seasonal: 78 },
      kpis: [
        { value: "16", label: "SKUs A/B tested in Q4" },
        { value: "+2.9%", label: "Median sales lift" },
        { value: "12 of 16", label: "Challenger won" },
      ],
      calcRows: [
        { label: "Revenue, SKUs not yet optimized in Q4", value: "$12.67M" },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Foundational lift", value: "$0.38M", variant: "subtotal" },
        {
          label: "Revenue in the 2 weeks after Cyber Monday and Holiday Gift Guide",
          value: "$45.67M",
        },
        { label: "× pilot lift rate", value: "3.0%" },
        { label: "Seasonal lift", value: "$1.37M", variant: "subtotal" },
      ],
      calcSummary: { label: "Opportunity in Q4", value: "$1.75M", variant: "total" },
      methodology:
        "Q4 revenue comes from Vendor Central history for Oct 1 – Dec 31. $12.67M × 3.0% = $0.38M. $45.67M × 3.0% = $1.37M. Together that is $1.75M.",
    },
    valueRealized: {
      id: "value-realized",
      tabLabel: "Value Realized",
      heading: "Value realized",
      periodBadge: "Oct 1 – Dec 31, 2026",
      trendBadge: { label: "+$80K this month", positive: true },
      heroAmountLabel: "$250K",
      heroBordered: true,
      foundationalLiftLabel: "Foundational lift",
      foundationalLiftAmount: "$160K",
      seasonalLiftLabel: "Seasonal lift",
      seasonalLiftAmount: "$90K",
      liftBarPct: { foundational: 64, seasonal: 36 },
      kpis: [
        { value: "40", label: "SKUs live" },
        { value: "3.2 days", label: "Median approve-to-live" },
        { value: "Q4", label: "Accruing this quarter" },
      ],
      calcRows: [],
      bodyCopy:
        "Counts only the 40 SKUs published in Q4 so far, accrued over the days their content was actually live in the Oct 1 – Dec 31 window.",
      cta: { label: "See SKU-level attribution in Agent Impact", href: "/impact" },
      methodology: "",
    },
  },
  secondaryStats: [
    {
      id: "working-days-saved",
      label: "Working days saved",
      value: "2.4",
      delta: "5% productivity boost WoW",
      deltaPositive: true,
      footnote: "40 actions taken · 19.3 analyst hours",
      calculation: {
        title: "Working days saved",
        rows: [
          { label: "SKUs published in Q4", value: "40" },
          { label: "Manual benchmark, per SKU", value: "30 min" },
          { label: "Agent, per SKU", value: "1 min" },
          { label: "Saved per SKU", value: "29 min" },
          { label: "Total saved", value: "19.3 hrs" },
        ],
        summaryRow: { label: "At an 8-hour working day", value: "2.4 days" },
        methodology:
          "Time saved counts only SKUs published in this quarter. 40 SKUs × 29 minutes = 19.3 hours, or 2.4 working days.",
      },
    },
    {
      id: "ai-rank",
      label: "AI rank",
      value: "#3",
      delta: "▲ 1 place vs prior week",
      deltaPositive: true,
      live: true,
      footnote: "Median position across 25 tracked prompts",
      calculation: {
        title: "AI rank",
        rows: [
          { label: "Tracked prompts", value: "25" },
          { label: "Prompts where you appear", value: "18" },
          { label: "Median position when cited", value: "#3" },
        ],
        summaryRow: { label: "Prior week in Q4", value: "#4" },
        methodology:
          "Standing in the Q4 window, not the full-year median. Prompts where you don't appear are excluded from the median.",
      },
    },
    {
      id: "ai-share-of-voice",
      label: "AI share of voice",
      value: "33.8%",
      delta: "▲ 1.4 pp WoW",
      deltaPositive: true,
      live: true,
      footnote: "Weighted, up from 32.4% the week before",
      calculation: {
        title: "AI share of voice",
        rows: [
          { label: "Your weighted share in Q4", value: "33.8%" },
          { label: "Prior week", value: "32.4%" },
          { label: "Closest competitor", value: "39%" },
        ],
        summaryRow: { label: "Prompts measured", value: "25" },
        methodology:
          "Share of brand citations in the Q4 prompt runs, weighted by position. 33.8% − 32.4% = 1.4 percentage points.",
      },
    },
  ],
  upNext: {
    items: [
      {
        id: "cm",
        name: "Cyber Monday",
        valueLabel: "$860K",
        publishBy: "Nov 20",
        skuCount: 261,
        goesLiveNote: "4 days later",
      },
    ],
  },
  streams: [
    {
      id: "retail-readiness",
      title: "Retail-readiness",
      context: "of catalog is retail-ready",
      skuCount: 96,
      valueLabel: "$128K",
      valueKind: "blocked",
      tone: "warning",
      readyPercent: 96,
      insight:
        "**96 SKUs** are missing required **Amazon attributes** in the Q4 catalog pull. Amazon won’t accept a content push until these are backfilled, so **$128K** of **PDP fixes** queued this quarter are stuck behind this.",
      remainingLabel: "92 more SKUs, $100K blocked in total.",
      buckets: [
        {
          id: "q4-rr-1",
          title: "Unit price missing",
          skuCount: 34,
          fillTime: "~1 min",
          valueThousands: 42,
          releasesThousands: 9,
          alsoNote: "26 also have thin Cyber Monday bullets",
        },
        {
          id: "q4-rr-2",
          title: "Item weight missing",
          skuCount: 24,
          fillTime: "~1 min",
          valueThousands: 32,
          releasesThousands: 6,
          alsoNote: "18 also missing burn-time specs",
        },
        {
          id: "q4-rr-3",
          title: "Safety & compliance docs missing",
          skuCount: 18,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 24,
          releasesThousands: 4,
          alsoNote: "12 also have title gaps",
        },
        {
          id: "q4-rr-4",
          title: "Material composition missing",
          skuCount: 12,
          fillTime: "~1 min",
          valueThousands: 18,
          releasesThousands: 3,
          alsoNote: "9 also have thin bullets",
        },
        {
          id: "q4-rr-5",
          title: "Country of origin missing",
          skuCount: 8,
          fillTime: "~1 min",
          valueThousands: 12,
          releasesThousands: 2,
          alsoNote: "6 also have title gaps",
        },
      ],
      rows: [
        {
          id: "q4-rr-r1",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "Unit price missing on the Q4 feed",
          impactThousands: 12,
        },
        {
          id: "q4-rr-r2",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Item weight missing",
          impactThousands: 8,
        },
        {
          id: "q4-rr-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Safety sheet not attached",
          impactThousands: 5,
        },
        {
          id: "q4-rr-r4",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Country of origin blank",
          impactThousands: 3,
        },
      ],
    },
    {
      id: "seasonal",
      title: "Seasonal",
      context: "Next up · Cyber Monday · Publish by Nov 20 ·",
      contextHighlight: "65 days to act",
      skuCount: 261,
      valueLabel: "$860K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**261 SKUs** are missing deal framing, promo keywords, or urgency language for **Cyber Monday**. Ranked by revenue, the **top 20** carry about **a third of the $860K**.",
      queueNote:
        "Holiday Gift Guide ($510K) is queued next — it opens here once the Cyber Monday window closes.",
      remainingLabel: "255 more SKUs worth $646K, ranked by impact.",
      buckets: [
        {
          id: "q4-sea-1",
          title: "No promo keyword in title",
          skuCount: 88,
          fillTime: "~3 min",
          valueThousands: 280,
          alsoNote: "Publish by Nov 20 · 54 also need deal terms in bullets",
        },
        {
          id: "q4-sea-2",
          title: "Bullets don't state the deal terms",
          skuCount: 64,
          fillTime: "~2 min",
          valueThousands: 220,
          alsoNote: "Cyber Monday window · 39 also missing urgency language",
        },
        {
          id: "q4-sea-3",
          title: "No Cyber Monday urgency language",
          skuCount: 48,
          fillTime: "~2 min",
          valueThousands: 160,
          alsoNote: "28 also missing a promo keyword in the title",
        },
        {
          id: "q4-sea-4",
          title: "Blocked — attributes missing first",
          skuCount: 36,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 120,
          alsoNote: "Seasonal copy can't publish until attributes are backfilled",
        },
        {
          id: "q4-sea-5",
          title: "Bundle contents not described",
          skuCount: 25,
          fillTime: "~2 min",
          valueThousands: 80,
          alsoNote: "Gift sets · 14 also missing a promo keyword",
        },
      ],
      rows: [
        {
          id: "q4-sea-r1",
          name: "Aurelle Candles Hearthwood Cedar Jar",
          asin: "B079KLGWGR",
          finding: "No Cyber Monday keyword in title",
          impactThousands: 64,
        },
        {
          id: "q4-sea-r2",
          name: "Aurelle Candles Amber Floral Soy Candle",
          asin: "B07GR5MSKD",
          finding: "Bullets don't state the deal terms",
          impactThousands: 48,
        },
        {
          id: "q4-sea-r3",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Bundle contents not described",
          impactThousands: 36,
        },
        {
          id: "q4-sea-r4",
          name: "Aurelle Candles Coastal Linen Large Jar",
          asin: "B00FLYWNYQ",
          finding: "No Cyber Monday urgency language",
          impactThousands: 28,
        },
        {
          id: "q4-sea-r5",
          name: "Aurelle Candles Pink Sands Tumbler",
          asin: "B003IH3JN4",
          finding: "Title truncated before the offer",
          impactThousands: 22,
        },
        {
          id: "q4-sea-r6",
          name: "Aurelle Candles Rasa Decorative Candle Duo",
          asin: "B08C4L7HC1",
          finding: "Bullets 4 and 5 empty",
          impactThousands: 16,
        },
      ],
    },
    {
      id: "pdp",
      title: "Always on optimization",
      context: "Q4 · SEO & AEO · No deadline",
      skuCount: 154,
      valueLabel: "$390K",
      valueKind: "potential",
      tone: "default",
      insight:
        "**154 SKUs** identified in Q4 are missing category keywords or the structured specs an **AI answer engine** needs to cite the listing.",
      remainingLabel: "149 more SKUs worth $264K, ranked by impact.",
      buckets: [
        {
          id: "q4-pdp-1",
          title: "Missing top category keywords in bullets",
          skuCount: 52,
          fillTime: "~2 min",
          valueThousands: 140,
          alsoNote: "SEO lift · 33 also missing a search term in the title",
        },
        {
          id: "q4-pdp-2",
          title: "No answer-ready specs for common prompts",
          skuCount: 40,
          fillTime: "~3 min",
          valueThousands: 100,
          alsoNote: "AEO lift · 24 also have thin comparison bullets",
        },
        {
          id: "q4-pdp-3",
          title: "Title missing key search term",
          skuCount: 28,
          fillTime: "~2 min",
          valueThousands: 70,
          alsoNote: "Always on · 18 overlap with missing category keywords",
        },
        {
          id: "q4-pdp-4",
          title: "Bullets don't answer comparison prompts",
          skuCount: 20,
          fillTime: "~2 min",
          valueThousands: 50,
          alsoNote: "AEO lift · 12 also missing answer-ready specs",
        },
        {
          id: "q4-pdp-5",
          title: "Blocked — attributes missing first",
          skuCount: 14,
          fillMode: "input",
          fillTime: "~15 min",
          valueThousands: 30,
          alsoNote: "SEO copy can't publish until attributes are backfilled",
        },
      ],
      rows: [
        {
          id: "q4-pdp-r1",
          name: "Aurelle Candles Citrus Zest Soy Jar",
          asin: "B00I0DI0Z6",
          finding: "Missing holiday category keywords in bullets",
          impactThousands: 42,
          findingType: "SEO",
        },
        {
          id: "q4-pdp-r2",
          name: "Aurelle Candles Noir Cherry Large Jar",
          asin: "B08NF9KBZ4",
          finding: "No answer-ready specs for gift prompts",
          impactThousands: 30,
          findingType: "AEO",
        },
        {
          id: "q4-pdp-r3",
          name: "Aurelle Candles Vanilla Tobacco Jar",
          asin: "B00FQK1H8C",
          finding: "Title missing 'soy jar'",
          impactThousands: 24,
          findingType: "SEO",
        },
        {
          id: "q4-pdp-r4",
          name: "Aurelle Candles Spiced Cedar 3-Wick",
          asin: "B00H8R3KM2",
          finding: "Bullets don't answer comparison prompts",
          impactThousands: 18,
          findingType: "AEO",
        },
        {
          id: "q4-pdp-r5",
          name: "Aurelle Candles Bergamot Grove Pillar Set",
          asin: "B00005UP2P",
          finding: "Missing hand-poured keyword",
          impactThousands: 12,
          findingType: "SEO",
        },
      ],
    },
  ],
}
